# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a2280a7d0147b8548d3fee8d072b3a32619b9019592b6b6a999a2367dca8c7935e374f95f0461106a2738c386d3ea0c03c48f890183c96a50a51efd696f9c72

test:
  secret_key_base: 754e026d4524d2e246d560a7495e1df3f53aee793934fef42ca98d1e339e644d404eb9fbc7c49930b36591357a0ba696c356e14fc79e9ecb5a5fca0c968a26ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
