# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)




Stadium.create({name:"Angel Stadium of Anaheim", team:"Los Angeles Angels of Anaheim", location:"Anaheim, CA", photo:"angels.jpg", history:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim .", year:1966, capacity: 41503, feature:"Food Court"})

Stadium.create({name:"AT&T Ballpark", team:"San Francisco Giants", location:"San Francisco, CA", photo:"giants.jpg", history:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim .", year:2000, capacity: 41915, feature:"Food Court"})

Stadium.create({name:"Busch Stadium", team:"St. Louis Cardinals", location:"St. Louis, MO", photo:"cardinals.jpg", history:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim .", year:2006, capacity: 43975, feature:"Food Court"})

Stadium.create({name:"Chase Field", team:"Arizona Diamondbacks", location:"Phoenix, AZ", photo:"diamondbacks.jpg", history:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim.", year:1998, capacity: 48519, feature:"The View"})

Stadium.create({name:"Citi Field", team:"New York Mets", location:"Queens, NY", photo:"mets.jpg", history:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim .", year:2009, capacity: 41922, feature:"Food Court"})

Stadium.create({name:"Citizens Bank Park", team:"Philadelphia Phillies", location:"Philadelphia, PA", photo:"phillies.jpg", history:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim .", year:2004, capacity: 43651, feature:"Food Court"})

Stadium.create({name:"Comerica Park", team:"Detroit Tigers", location:"Detroit, MI", photo:"tigers.jpg", history:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. m ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim .", year:2000, capacity: 41574, feature:"Food Court"})

Stadium.create({name:"Coors Field", team:"Colorado Rockies", location:"Denver, CO", photo:"rockies.jpg", history:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. m ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim .", year:1995, capacity: 50398, feature:"Rooftop Bar"})

Stadium.create({name:"Dodger Stadium", team:"Los Angeles Dodgers", location:"Los Angeles, Ca", photo:"dodger.jpg", history:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. m ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. m ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim .", year:1962, capacity: 56000, feature:"Dodger Dog"})

Stadium.create({name:"Fenway Park", team:"Boston Red Sox", location:"Boston, MA", photo:"redsox.jpg", history:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. m ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim .", year:1912, capacity: 37673, feature:"Green Monster"})

Stadium.create({name:"Globe Life Park in Arlington", team:"Texas Rangers", location:"Arlington, TX", photo:"rangers.jpg", history:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. m ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim . consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim .", year:1994, capacity: 48114, feature:"Food Court"})

Stadium.create({name:"Great American Ball Park", team:"Cincinnati Reds", location:"Cincinnati, OH", photo:"reds.jpg", history:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. m ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim .", year:2003, capacity: 42319, feature:"Great City"})

Stadium.create({name:"Kauffman Stadium", team:"Kansas City Royals", location:"Kansas City, MO", photo:"royals.jpg", history:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. m ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim it, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim .", year:1973, capacity: 37903, feature:"Jumbotron"})

Stadium.create({name:"Marlins Park", team:"Miami Marlins", location:"Miami, FL", photo:"marlins.jpg", history:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. m ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim it, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim .", year:2012, capacity: 36742, feature:"Food Court"})

Stadium.create({name:"Miller Park", team:"Milwaukee Brewers", location:"Milwaukee, WI", photo:"brewers.jpg", history:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. m ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim it, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut  tempor incididunt ut labore et dolore magna aliqua. Ut enim it, sed do eiusmod tempor incididunt ut labore etenim .", year:2001, capacity: 41900, feature:"The Beer"})

Stadium.create({name:"Minute Maid Park", team:"Houston Astros", location:"Houston, TX", photo:"atros.jpg", history:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. m ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim it, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim .", year:2000, capacity: 41574, feature:"Food Court"})

Stadium.create({name:"Nationals Park", team:"Washington Nationals", location:"Washington, D.C.", photo:"nationals.jpg", history:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. m ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim it, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim incididunt ut labore et dolore magna aliqua. m ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim it, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim .", year:2008, capacity: 41888, feature:"America"})

Stadium.create({name:"O.co Coliseum", team:"Oakland Athletics", location:"Oakland, CA", photo:"athletics.jpg", history:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. m ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim it, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim .", year:1966, capacity: 35067, feature:"Food Court"})

Stadium.create({name:"Oriole Park at Camden Yards", team:"Baltimore Orioles", location:"Baltimore, MD", photo:"orioles.jpg", history:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. m ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim it, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim .", year:1992, capacity: 45971, feature:"Food Court"})

Stadium.create({name:"Petco Park", team:"San Diego Padres", location:"San Diego, CA", photo:"padres.jpg", history:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. m ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim it, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim .", year:2004, capacity: 41164, feature:"Ocean"})

Stadium.create({name:"PNC Park", team:"Pittsburgh Pirates", location:"Pittsburgh, PA", photo:"pirate.jpg", history:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. m ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim it, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim .", year:2001, capacity: 38362, feature:"Food Court"})

Stadium.create({name:"Progressive Field", team:"Cleveland Indians", location:"Cleveland, OH", photo:"indians.jpg", history:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. m ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim it, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim  sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim it, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim.", year:1994, capacity: 37675, feature:"Food Court"})

Stadium.create({name:"Rogers Centre", team:"Toronto Blue Jays", location:"Toronto, Ontario, CA", photo:"jays.jpg", history:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. m ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim it, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim incididunt ut labore et dolore magna aliqua. Ut enim .incididunt ut labore et dolore magna aliqua. Ut enim ..", year:1989, capacity: 49282, feature:"Food Court"})

Stadium.create({name:"Safeco Field", team:"Seattle Mariners", location:"Seattle, WA", photo:"mariners.jpg", history:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. m ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim it, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim .", year:1999, capacity: 47574, feature:"Food Court"})

Stadium.create({name:"Target Field", team:"Minnesota Twins", location:"Minneapolis, MN", photo:"twins.jpg", history:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. m ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim it, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim .", year:2010, capacity: 39021, feature:"Food Court"})

Stadium.create({name:"Tropicana Field", team:"Tampa Bay Rays", location:"St. Petersburg, FL", photo:"rays.jpg", history:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. m ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim it, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim .", year:1990, capacity: 31042, feature:"Food Court"})

Stadium.create({name:"Turner Field", team:"Atlanta Braves", location:"Atlanta, GA", photo:"braves.jpg", history:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. m ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. m ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim it, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim .", year:1996, capacity: 49586, feature:"Food Court"})

Stadium.create({name:"U.S. Cellular Field", team:"Chicago White Sox", location:"Chicago, IL", photo:"whitesox.jpg", history:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. m ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim it, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim .", year:1991, capacity: 40615, feature:"Right Field Bar"})

Stadium.create({name:"Wrigley Field", team:"Chicago Cubs", location:"Chicago, IL", photo:"cubs.jpg", history:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. m ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim it, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim .", year:1914, capacity: 42495, feature:"Its History"})

Stadium.create({name:"Yankee Stadium", team:"New York Yankees", location:"Bronx, NY", photo:"yankees.jpg", history:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut laboreet dolore magna aliqua. m ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim it, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim .", year:2009, capacity: 49642, feature:"Food Court"})
